name: "setup-atopile"
description: "Setup atopile CLI"
branding:
  icon: "package"
  color: "orange"

inputs:
  ato-config:
    description: "Path to ato.yaml config, based on which to determine the version to run"
    required: false
    default: ""
  version:
    description: "A specific version of atopile to use"
    required: false
    default: ""
  docker-tag:
    description: "A Docker image tag to pull (e.g., 'feature-fabll_part2', 'pr-123', 'sha-abc1234'). Overrides version/ato-config."
    required: false
    default: ""
  working-directory:
    description: "Working directory where to look for ato.yaml config"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - uses: astral-sh/setup-uv@v5
      with:
        enable-cache: false
        pyproject-file: "${{ github.action_path }}/pyproject.toml"

    # When docker-tag is specified, pull that specific tag directly
    - name: Pull atopile container by tag
      if: ${{ inputs.docker-tag != '' }}
      run: >
        docker pull
        "ghcr.io/atopile/atopile-kicad:${{ inputs.docker-tag }}"
      shell: bash

    - name: Tag atopile container (docker-tag)
      if: ${{ inputs.docker-tag != '' }}
      run: >
        docker tag
        "ghcr.io/atopile/atopile-kicad:${{ inputs.docker-tag }}"
        "atopile-local"
      shell: bash

    # When docker-tag is NOT specified, use the standard version resolution
    - id: determine-atopile-version
      if: ${{ inputs.docker-tag == '' }}
      run: uv run --project "${{ github.action_path }}" --directory "${{ inputs.working-directory }}" python "${{ github.action_path }}/main.py" >> $GITHUB_OUTPUT
      shell: bash
      env:
        ATO_CONFIG: ${{ inputs.ato-config }}
        SPECIFIED_VERSION: ${{ inputs.version }}

    - name: Pull atopile container
      if: ${{ inputs.docker-tag == '' }}
      run: >
        docker pull
        "ghcr.io/atopile/atopile-kicad:${{ steps.determine-atopile-version.outputs.version }}"
      shell: bash

    - name: Tag atopile container
      if: ${{ inputs.docker-tag == '' }}
      run: >
        docker tag
        "ghcr.io/atopile/atopile-kicad:${{ steps.determine-atopile-version.outputs.version }}"
        "atopile-local"
      shell: bash

    - name: Install alias
      run: echo "${{ github.action_path }}/bin" >> $GITHUB_PATH
      shell: bash
